export const backgroundClasses = [
  { value: 'bg-transparent', label: 'bg-transparent' },
  { value: 'bg-current', label: 'bg-current' },
  { value: 'bg-black', label: 'bg-black' },
  { value: 'bg-white', label: 'bg-white' },
  { value: 'bg-gray-100', label: 'bg-gray-100' },
  { value: 'bg-gray-200', label: 'bg-gray-200' },
  { value: 'bg-gray-300', label: 'bg-gray-300' },
  { value: 'bg-gray-400', label: 'bg-gray-400' },
  { value: 'bg-gray-500', label: 'bg-gray-500' },
  { value: 'bg-gray-600', label: 'bg-gray-600' },
  { value: 'bg-gray-700', label: 'bg-gray-700' },
  { value: 'bg-gray-800', label: 'bg-gray-800' },
  { value: 'bg-gray-900', label: 'bg-gray-900' },
  { value: 'bg-red-100', label: 'bg-red-100' },
  { value: 'bg-red-200', label: 'bg-red-200' },
  { value: 'bg-red-300', label: 'bg-red-300' },
  { value: 'bg-red-400', label: 'bg-red-400' },
  { value: 'bg-red-500', label: 'bg-red-500' },
  { value: 'bg-red-600', label: 'bg-red-600' },
  { value: 'bg-red-700', label: 'bg-red-700' },
  { value: 'bg-red-800', label: 'bg-red-800' },
  { value: 'bg-red-900', label: 'bg-red-900' },
  { value: 'bg-yellow-100', label: 'bg-yellow-100' },
  { value: 'bg-yellow-200', label: 'bg-yellow-200' },
  { value: 'bg-yellow-300', label: 'bg-yellow-300' },
  { value: 'bg-yellow-400', label: 'bg-yellow-400' },
  { value: 'bg-yellow-500', label: 'bg-yellow-500' },
  { value: 'bg-yellow-600', label: 'bg-yellow-600' },
  { value: 'bg-yellow-700', label: 'bg-yellow-700' },
  { value: 'bg-yellow-800', label: 'bg-yellow-800' },
  { value: 'bg-yellow-900', label: 'bg-yellow-900' },
  { value: 'bg-green-100', label: 'bg-green-100' },
  { value: 'bg-green-200', label: 'bg-green-200' },
  { value: 'bg-green-300', label: 'bg-green-300' },
  { value: 'bg-green-400', label: 'bg-green-400' },
  { value: 'bg-green-500', label: 'bg-green-500' },
  { value: 'bg-green-600', label: 'bg-green-600' },
  { value: 'bg-green-700', label: 'bg-green-700' },
  { value: 'bg-green-800', label: 'bg-green-800' },
  { value: 'bg-green-900', label: 'bg-green-900' },
  { value: 'bg-blue-100', label: 'bg-blue-100' },
  { value: 'bg-blue-200', label: 'bg-blue-200' },
  { value: 'bg-blue-300', label: 'bg-blue-300' },
  { value: 'bg-blue-400', label: 'bg-blue-400' },
  { value: 'bg-blue-500', label: 'bg-blue-500' },
  { value: 'bg-blue-600', label: 'bg-blue-600' },
  { value: 'bg-blue-700', label: 'bg-blue-700' },
  { value: 'bg-blue-800', label: 'bg-blue-800' },
  { value: 'bg-blue-900', label: 'bg-blue-900' },
  { value: 'bg-indigo-100', label: 'bg-indigo-100' },
  { value: 'bg-indigo-200', label: 'bg-indigo-200' },
  { value: 'bg-indigo-300', label: 'bg-indigo-300' },
  { value: 'bg-indigo-400', label: 'bg-indigo-400' },
  { value: 'bg-indigo-500', label: 'bg-indigo-500' },
  { value: 'bg-indigo-600', label: 'bg-indigo-600' },
  { value: 'bg-indigo-700', label: 'bg-indigo-700' },
  { value: 'bg-indigo-800', label: 'bg-indigo-800' },
  { value: 'bg-indigo-900', label: 'bg-indigo-900' },
  { value: 'bg-purple-100', label: 'bg-purple-100' },
  { value: 'bg-purple-200', label: 'bg-purple-200' },
  { value: 'bg-purple-300', label: 'bg-purple-300' },
  { value: 'bg-purple-400', label: 'bg-purple-400' },
  { value: 'bg-purple-500', label: 'bg-purple-500' },
  { value: 'bg-purple-600', label: 'bg-purple-600' },
  { value: 'bg-purple-700', label: 'bg-purple-700' },
  { value: 'bg-purple-800', label: 'bg-purple-800' },
  { value: 'bg-purple-900', label: 'bg-purple-900' },
  { value: 'bg-pink-100', label: 'bg-pink-100' },
  { value: 'bg-pink-200', label: 'bg-pink-200' },
  { value: 'bg-pink-300', label: 'bg-pink-300' },
  { value: 'bg-pink-400', label: 'bg-pink-400' },
  { value: 'bg-pink-500', label: 'bg-pink-500' },
  { value: 'bg-pink-600', label: 'bg-pink-600' },
  { value: 'bg-pink-700', label: 'bg-pink-700' },
  { value: 'bg-pink-800', label: 'bg-pink-800' },
  { value: 'bg-pink-900', label: 'bg-pink-900' },
];

export const fontColorClasses = [
  { value: 'text-transparent', label: 'text-transparent' },
  { value: 'text-current', label: 'text-current' },
  { value: 'text-black', label: 'text-black' },
  { value: 'text-white', label: 'text-white' },
  { value: 'text-gray-100', label: 'text-gray-100' },
  { value: 'text-gray-200', label: 'text-gray-200' },
  { value: 'text-gray-300', label: 'text-gray-300' },
  { value: 'text-gray-400', label: 'text-gray-400' },
  { value: 'text-gray-500', label: 'text-gray-500' },
  { value: 'text-gray-600', label: 'text-gray-600' },
  { value: 'text-gray-700', label: 'text-gray-700' },
  { value: 'text-gray-800', label: 'text-gray-800' },
  { value: 'text-gray-900', label: 'text-gray-900' },
  { value: 'text-red-100', label: 'text-red-100' },
  { value: 'text-red-200', label: 'text-red-200' },
  { value: 'text-red-300', label: 'text-red-300' },
  { value: 'text-red-400', label: 'text-red-400' },
  { value: 'text-red-500', label: 'text-red-500' },
  { value: 'text-red-600', label: 'text-red-600' },
  { value: 'text-red-700', label: 'text-red-700' },
  { value: 'text-red-800', label: 'text-red-800' },
  { value: 'text-red-900', label: 'text-red-900' },
  { value: 'text-yellow-100', label: 'text-yellow-100' },
  { value: 'text-yellow-200', label: 'text-yellow-200' },
  { value: 'text-yellow-300', label: 'text-yellow-300' },
  { value: 'text-yellow-400', label: 'text-yellow-400' },
  { value: 'text-yellow-500', label: 'text-yellow-500' },
  { value: 'text-yellow-600', label: 'text-yellow-600' },
  { value: 'text-yellow-700', label: 'text-yellow-700' },
  { value: 'text-yellow-800', label: 'text-yellow-800' },
  { value: 'text-yellow-900', label: 'text-yellow-900' },
  { value: 'text-green-100', label: 'text-green-100' },
  { value: 'text-green-200', label: 'text-green-200' },
  { value: 'text-green-300', label: 'text-green-300' },
  { value: 'text-green-400', label: 'text-green-400' },
  { value: 'text-green-500', label: 'text-green-500' },
  { value: 'text-green-600', label: 'text-green-600' },
  { value: 'text-green-700', label: 'text-green-700' },
  { value: 'text-green-800', label: 'text-green-800' },
  { value: 'text-green-900', label: 'text-green-900' },
  { value: 'text-blue-100', label: 'text-blue-100' },
  { value: 'text-blue-200', label: 'text-blue-200' },
  { value: 'text-blue-300', label: 'text-blue-300' },
  { value: 'text-blue-400', label: 'text-blue-400' },
  { value: 'text-blue-500', label: 'text-blue-500' },
  { value: 'text-blue-600', label: 'text-blue-600' },
  { value: 'text-blue-700', label: 'text-blue-700' },
  { value: 'text-blue-800', label: 'text-blue-800' },
  { value: 'text-blue-900', label: 'text-blue-900' },
  { value: 'text-indigo-100', label: 'text-indigo-100' },
  { value: 'text-indigo-200', label: 'text-indigo-200' },
  { value: 'text-indigo-300', label: 'text-indigo-300' },
  { value: 'text-indigo-400', label: 'text-indigo-400' },
  { value: 'text-indigo-500', label: 'text-indigo-500' },
  { value: 'text-indigo-600', label: 'text-indigo-600' },
  { value: 'text-indigo-700', label: 'text-indigo-700' },
  { value: 'text-indigo-800', label: 'text-indigo-800' },
  { value: 'text-indigo-900', label: 'text-indigo-900' },
  { value: 'text-purple-100', label: 'text-purple-100' },
  { value: 'text-purple-200', label: 'text-purple-200' },
  { value: 'text-purple-300', label: 'text-purple-300' },
  { value: 'text-purple-400', label: 'text-purple-400' },
  { value: 'text-purple-500', label: 'text-purple-500' },
  { value: 'text-purple-600', label: 'text-purple-600' },
  { value: 'text-purple-700', label: 'text-purple-700' },
  { value: 'text-purple-800', label: 'text-purple-800' },
  { value: 'text-purple-900', label: 'text-purple-900' },
  { value: 'text-pink-100', label: 'text-pink-100' },
  { value: 'text-pink-200', label: 'text-pink-200' },
  { value: 'text-pink-300', label: 'text-pink-300' },
  { value: 'text-pink-400', label: 'text-pink-400' },
  { value: 'text-pink-500', label: 'text-pink-500' },
  { value: 'text-pink-600', label: 'text-pink-600' },
  { value: 'text-pink-700', label: 'text-pink-700' },
  { value: 'text-pink-800', label: 'text-pink-800' },
  { value: 'text-pink-900', label: 'text-pink-900' },
];

export const borderRadiusClasses = [
  'rounded-none',
  'rounded-sm	',
  'rounded',
  'rounded-md',
  'rounded-lg	',
  'rounded-xl	',
  'rounded-2xl',
  'rounded-3xl',
  'rounded-full',
  'rounded-t-none',
  'rounded-t-sm',
  'rounded-t',
  'rounded-t-md',
  'rounded-t-lg',
  'rounded-t-xl',
  'rounded-t-2xl',
  'rounded-t-3xl',
  'rounded-t-full',
  'rounded-r-none',
  'rounded-r-sm',
  'rounded-r	',
  'rounded-r-md',
  'rounded-r-lg',
  'rounded-r-xl',
  'rounded-r-2xl',
  'rounded-r-3xl',
  'rounded-r-full',
  'rounded-b-none',
  'rounded-b-sm',
  'rounded-b',
  'rounded-b-md',
  'rounded-b-lg',
  'rounded-b-xl',
  'rounded-b-2xl',
  'rounded-b-3xl',
  'rounded-b-full',
  'rounded-l-none',
  'rounded-l-sm',
  'rounded-l',
  'rounded-l-md',
  'rounded-l-lg',
  'rounded-l-xl',
  'rounded-l-2xl',
  'rounded-l-3xl',
  'rounded-l-full',
  'rounded-tl-none',
  'rounded-tl-sm',
  'rounded-tl	',
  'rounded-tl-md',
  'rounded-tl-lg',
  'rounded-tl-xl',
  'rounded-tl-2xl',
  'rounded-tl-3xl',
  'rounded-tl-full',
  'rounded-tr-none',
  'rounded-tr-sm',
  'rounded-tr	',
  'rounded-tr-md',
  'rounded-tr-lg',
  'rounded-tr-xl',
  'rounded-tr-2xl',
  'rounded-tr-3xl',
  'rounded-tr-full',
  'rounded-br-none',
  'rounded-br-sm',
  'rounded-br	',
  'rounded-br-md',
  'rounded-br-lg',
  'rounded-br-xl',
  'rounded-br-2xl',
  'rounded-br-3xl',
  'rounded-br-full',
  'rounded-bl-none',
  'rounded-bl-sm',
  'rounded-bl	',
  'rounded-bl-md',
  'rounded-bl-lg',
  'rounded-bl-xl',
  'rounded-bl-2xl',
  'rounded-bl-3xl',
  'rounded-bl-full',
];

export const paddingClasses = {
  prepends: ['p', 'px', 'py', 'pt', 'pr', 'pb', 'pl'],
  values: [
    '-0',
    '-px',
    '-0.5',
    '-1',
    '-1.5',
    '-2',
    '-2.5',
    '-3',
    '-3.5',
    '-4',
    '-5',
    '-6',
    '-7',
    '-8',
    '-9',
    '-10',
    '-11',
    '-12',
    '-14',
    '-16',
    '-20',
    '-24',
    '-28',
    '-32',
    '-36',
    '-40',
    '-44',
    '-48',
    '-52',
    '-56',
    '-60',
    '-64',
    '-72',
    '-80',
    '-96',
  ],
};

export const fontSizeClasses = [
  'text-xs',
  'text-sm',
  'text-base',
  'text-lg',
  'text-xl',
  'text-2xl',
  'text-3xl',
  'text-4xl',
  'text-5xl',
  'text-6xl',
  'text-7xl',
  'text-8xl',
  'text-9xl',
];

export const fontWeightClasses = [
  'font-thin',
  'font-extralight',
  'font-light',
  'font-normal',
  'font-medium',
  'font-semibold',
  'font-bold',
  'font-extrabold',
  'font-black',
];
